import type {
  Addon,
  BlockedDate,
  BusinessHours,
  BusinessSettings,
  Service,
} from './types';

/**
 * Safe demo data used only when the Neon-backed API is unreachable.
 * The real backend data takes over automatically once DATABASE_URL/JWT_SECRET are configured.
 */

const NOW_ISO = new Date('2026-01-01T12:00:00Z').toISOString();

export const demoServices: Service[] = [
  {
    id: 'demo-svc-sectional-kitchen',
    name: 'Sectional Clean — Gourmet Kitchen Focus',
    description: 'A focused, single-section clean for just the kitchen. Book on its own or alongside other sections.',
    duration_minutes: 45,
    price: 49,
    is_active: true,
    created_at: NOW_ISO,
    category: 'sectional',
    tasks: [
      'Surface Sanitation — countertops, backsplashes, breakfast bars',
      'Appliance Facades — fridge, oven, dishwasher exterior',
      'Stovetop Restore — burners, grates, knobs',
      'Cavity Clean — microwave inside/out',
      'Fixtures & Basin — sink/faucet polish',
      'Floor Care — vacuum and damp-mop',
    ],
    base_bedrooms: 1,
    base_bathrooms: 1,
    bedroom_modifier: 0,
    bathroom_modifier: 0,
  },
  {
    id: 'demo-svc-sectional-bathroom',
    name: 'Sectional Clean — Spa Bathroom Focus',
    description: 'A focused, single-section clean for just one bathroom. Book on its own or alongside other sections.',
    duration_minutes: 30,
    price: 49,
    is_active: true,
    created_at: NOW_ISO,
    category: 'sectional',
    tasks: [
      'Sanitary Porcelain — toilet bowl, base, tank, flusher',
      'Shower & Tub — soap scum removal from tile, glass doors, basins',
      'Vanity & Mirror — sink basin, faucet polish, mirrors',
      'Floor Care — bath mats shake, vacuum, hand-mop tiles',
    ],
    base_bedrooms: 1,
    base_bathrooms: 1,
    bedroom_modifier: 0,
    bathroom_modifier: 0,
  },
  {
    id: 'demo-svc-sectional-bedroom',
    name: 'Sectional Clean — Sleep & Lounge Focus (Per Room)',
    description: "A focused, single-section clean for one bedroom or lounge room. Book once per room you'd like covered.",
    duration_minutes: 30,
    price: 49,
    is_active: true,
    created_at: NOW_ISO,
    category: 'sectional',
    tasks: [
      'Dusting Mastery — nightstands, dressers, TV stands, screens',
      'Linen Service — straighten/replace bedsheets',
      'High-Touch Wipe — door handles, switches, remotes',
      'Floor Care — edge vacuuming/mopping',
    ],
    base_bedrooms: 1,
    base_bathrooms: 1,
    bedroom_modifier: 0,
    bathroom_modifier: 0,
  },
  {
    id: 'demo-svc-standard',
    name: 'Standard Maintenance Cleaning (1 Bed / 1 Bath)',
    description: 'A full-home maintenance clean covering kitchen, bathrooms, bedrooms, and living areas. Price scales with home size — add bedrooms/bathrooms when booking.',
    duration_minutes: 120,
    price: 129,
    is_active: true,
    created_at: NOW_ISO,
    category: 'standard',
    tasks: [
      'Kitchen — countertop perimeters/backsplashes',
      'Kitchen — stovetop exterior',
      'Kitchen — major appliance exteriors',
      'Kitchen — microwave interior/turntable',
      'Kitchen — spot-wipe cabinet doors',
      'Kitchen — sanitize sink/polish chrome',
      'Kitchen — sweep and damp-mop',
      'Bathrooms — disinfect/scrub toilet',
      'Bathrooms — clean tub/shower walls/fixtures',
      'Bathrooms — wipe vanity top/sink/faucet',
      'Bathrooms — streak-free mirror cleaning',
      'Bathrooms — empty trash liner/wipe canister',
      'Bathrooms — mop tiles with disinfectant',
      'Bedrooms & Living — dust accessible surfaces/shelves/decor',
      'Bedrooms & Living — straighten bed linens/fluff pillows',
      'Bedrooms & Living — vacuum rugs/carpets/under low furniture',
      'Bedrooms & Living — dust reachable sills/baseboards',
      'Bedrooms & Living — empty all trash bins',
    ],
    base_bedrooms: 1,
    base_bathrooms: 1,
    bedroom_modifier: 30,
    bathroom_modifier: 40,
  },
  {
    id: 'demo-svc-deep-cleaning',
    name: 'Deep Cleaning',
    description: "A dramatically more thorough clean — interiors, tracks, grout, and every surface a standard visit doesn't reach. Price and duration are placeholders pending confirmation.",
    duration_minutes: 210,
    price: 0,
    is_active: true,
    created_at: NOW_ISO,
    category: 'deep',
    tasks: [
      'Kitchen — oven interior',
      'Kitchen — refrigerator interior',
      'Kitchen — freezer',
      'Kitchen — cabinet fronts (entire kitchen)',
      'Kitchen — hood filters',
      'Kitchen — window tracks',
      'Kitchen — light fixtures',
      'Bathrooms — tile grout',
      'Bathrooms — hard water removal',
      'Bathrooms — exhaust fan',
      'Bathrooms — under sink exterior',
      'Bathrooms — detailed fixtures',
      'Bedrooms — under bed vacuum',
      'Bedrooms — closet floor',
      'Bedrooms — baseboards scrubbed',
      'Bedrooms — window tracks',
      'Bedrooms — doors',
      'Living Room — furniture moved where safe',
      'Living Room — behind couch',
      'Living Room — window interiors',
      'Living Room — blinds',
      'Living Room — ceiling fan',
      'Entire Home — air vents',
      'Entire Home — baseboards',
      'Entire Home — interior doors',
      'Entire Home — frames',
      'Entire Home — trim',
      'Entire Home — window sills',
    ],
    base_bedrooms: 1,
    base_bathrooms: 1,
    bedroom_modifier: 0,
    bathroom_modifier: 0,
  },
  {
    id: 'demo-svc-turnover',
    name: 'Move-In / Move-Out Turnover (Empty Unit)',
    description: 'A full turnover clean for a completely empty unit — required for accurate pricing and scope. Price scales with bedrooms/bathrooms — add them when booking.',
    duration_minutes: 240,
    price: 249,
    is_active: true,
    created_at: NOW_ISO,
    category: 'turnover',
    tasks: [
      'Vacuum/wipe inside all empty cabinets/drawers',
      'Closet Restoration — shelves/rods',
      'Appliance Overhaul — inside/out oven, fridge, freezer, dishwasher',
      'Fixtures & Trim cleaning',
      'Entryway & Doors wipe-down',
      'Restorative Floor Prep — edge vacuum/double mop',
      'Small trash bagging',
      'Complete switch/outlet cover sanitization',
    ],
    base_bedrooms: 1,
    base_bathrooms: 1,
    bedroom_modifier: 45,
    bathroom_modifier: 45,
  },
];

export const demoAddons: Addon[] = [
  { id: 'demo-addon-laundry', slug: 'laundry-service', name: 'Laundry Service', description: 'Wash, dry, and fold a load of laundry during the visit — iron available on request.', price: 0, duration_minutes: 0, is_active: true, created_at: NOW_ISO },
  { id: 'demo-addon-fridge', slug: 'inside-refrigerator', name: 'Inside Refrigerator', description: 'Full interior clean of the refrigerator — shelves, drawers, and door bins.', price: 0, duration_minutes: 0, is_active: true, created_at: NOW_ISO },
  { id: 'demo-addon-oven', slug: 'inside-oven', name: 'Inside Oven', description: 'Full interior clean of the oven cavity, racks, and door glass.', price: 0, duration_minutes: 0, is_active: true, created_at: NOW_ISO },
  { id: 'demo-addon-pet-hair', slug: 'pet-hair-removal', name: 'Pet Hair Removal', description: 'Extra pass to remove pet hair from furniture, floors, and upholstery.', price: 0, duration_minutes: 0, is_active: true, created_at: NOW_ISO },
  { id: 'demo-addon-balcony', slug: 'balcony-cleaning', name: 'Balcony Cleaning', description: 'Sweep and wipe-down of balcony surfaces and railings.', price: 0, duration_minutes: 0, is_active: true, created_at: NOW_ISO },
  { id: 'demo-addon-windows', slug: 'interior-windows', name: 'Interior Windows', description: 'Interior glass cleaning for accessible windows.', price: 0, duration_minutes: 0, is_active: true, created_at: NOW_ISO },
  { id: 'demo-addon-blinds', slug: 'blind-cleaning', name: 'Blind Cleaning', description: 'Dust and wipe-down of blinds, slat by slat.', price: 0, duration_minutes: 0, is_active: true, created_at: NOW_ISO },
  { id: 'demo-addon-walls', slug: 'wall-spot-cleaning', name: 'Wall Spot Cleaning', description: 'Spot cleaning of marks and scuffs on walls.', price: 0, duration_minutes: 0, is_active: true, created_at: NOW_ISO },
  { id: 'demo-addon-garage', slug: 'garage-sweep', name: 'Garage Sweep', description: 'Sweep and general tidy of garage floor space.', price: 0, duration_minutes: 0, is_active: true, created_at: NOW_ISO },
  { id: 'demo-addon-patio', slug: 'patio-cleaning', name: 'Patio Cleaning', description: 'Sweep and wipe-down of patio surfaces and furniture.', price: 0, duration_minutes: 0, is_active: true, created_at: NOW_ISO },
];

export const demoBusinessHours: BusinessHours[] = [
  { id: 'h-0', weekday: 0, is_open: false, start_time: '09:00:00', end_time: '17:00:00' },
  { id: 'h-1', weekday: 1, is_open: true,  start_time: '09:00:00', end_time: '17:00:00' },
  { id: 'h-2', weekday: 2, is_open: true,  start_time: '09:00:00', end_time: '17:00:00' },
  { id: 'h-3', weekday: 3, is_open: true,  start_time: '09:00:00', end_time: '17:00:00' },
  { id: 'h-4', weekday: 4, is_open: true,  start_time: '09:00:00', end_time: '17:00:00' },
  { id: 'h-5', weekday: 5, is_open: true,  start_time: '09:00:00', end_time: '17:00:00' },
  { id: 'h-6', weekday: 6, is_open: true,  start_time: '08:00:00', end_time: '14:00:00' },
];

export const demoBlockedDates: BlockedDate[] = [];

export const demoSettings: BusinessSettings = {
  id: 'demo-settings',
  business_name: 'Primax Group LLC',
  business_email: 'info@primaxgroupllc.com',
  business_phone: '(312) 296-5589',
  business_address: '332 S Michigan Ave, 9th Floor, Chicago, IL 60604',
  slot_interval_minutes: 30,
  booking_notice_hours: 2,
  created_at: NOW_ISO,
};
